config/routes.rb
Rails.application.routes.draw do
  resources :personal_preferences
  root 'personal_preferences#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personal_preference.rb
class PersonalPreference < ApplicationRecord
  enum favorite_animal: { cats: 0, dogs: 1}
  validates :name, uniqueness: true, presence: true
  validates :favorite_color, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/personal_preferences_controller.rb
class PersonalPreferencesController < ApplicationController
  before_action :set_personal_preference, only: [:show, :edit, :update, :destroy]

  # GET /personal_preferences
  # GET /personal_preferences.json
  def index
    @personal_preferences = PersonalPreference.all
  end

  # GET /personal_preferences/1
  # GET /personal_preferences/1.json
  def show
  end

  # GET /personal_preferences/new
  def new
    @personal_preference = PersonalPreference.new
  end

  # GET /personal_preferences/1/edit
  def edit
  end

  # POST /personal_preferences
  # POST /personal_preferences.json
  def create
    @personal_preference = PersonalPreference.new(personal_preference_params)

    respond_to do |format|
      if @personal_preference.save
        format.html { redirect_to @personal_preference, notice: 'Personal preference was successfully created.' }
        format.json { render :show, status: :created, location: @personal_preference }
      else
        format.html { render :new }
        format.json { render json: @personal_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_preferences/1
  # PATCH/PUT /personal_preferences/1.json
  def update
    respond_to do |format|
      if @personal_preference.update(personal_preference_params)
        format.html { redirect_to @personal_preference, notice: 'Personal preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_preference }
      else
        format.html { render :edit }
        format.json { render json: @personal_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_preferences/1
  # DELETE /personal_preferences/1.json
  def destroy
    @personal_preference.destroy
    respond_to do |format|
      format.html { redirect_to personal_preferences_url, notice: 'Personal preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_preference
      @personal_preference = PersonalPreference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_preference_params
      params.require(:personal_preference).permit(:name, :favorite_color, :favorite_animal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personal_preferences_helper.rb
module PersonalPreferencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='container'>
        <%= yield %>
  </div>
  </body>
</html>

app/views/personal_preferences/_form.html.erb
<%= simple_form_for(@personal_preference) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :favorite_color %>
    <br>
    <label>Select Favorite Animal:</label>
    <%= f.select :favorite_animal, PersonalPreference.favorite_animals.keys.to_a, {} %>
  </div>
   <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/personal_preferences/edit.html.erb
<h1>Editing Personal Preference</h1>

<%= render 'form', personal_preference: @personal_preference %>

<%= link_to 'Show', @personal_preference %> |
<%= link_to 'Back', personal_preferences_path %>

app/views/personal_preferences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal Preferences</h1>



<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Favorite color</th>
      <th>Favorite animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_preferences.each do |personal_preference| %>
      <tr>
        <td><%= personal_preference.name %></td>
        <td><%= personal_preference.favorite_color %></td>
        <td><%= personal_preference.favorite_animal %></td>
        <td><%= link_to 'Show', personal_preference %></td>
        <td><%= link_to 'Edit', edit_personal_preference_path(personal_preference) %></td>
        <td><%= link_to 'Destroy', personal_preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal Preference', new_personal_preference_path %>

app/views/personal_preferences/new.html.erb
<h1>New Personal Preference</h1>

<%= render 'form', personal_preference: @personal_preference %>

<%= link_to 'Back', personal_preferences_path %>

app/views/personal_preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @personal_preference.name %>
</p>

<p>
  <strong>Favorite color:</strong>
  <%= @personal_preference.favorite_color %>
</p>

<p>
  <strong>Favorite animal:</strong>
  <%= @personal_preference.favorite_animal %>
</p>

<%= link_to 'Edit', edit_personal_preference_path(@personal_preference) %> |
<%= link_to 'Back', personal_preferences_path %>